mysql: &mysql
  adapter: mysql2
  host: "db.coding4coffee.org"
  port: 3306
  username: "diaspora_test"
  password: "rJyJG2RsP825TW4e"
#  socket: /tmp/mysql.sock
  charset: utf8
  collation: utf8_bin

postgres: &postgres
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password:
  encoding: unicode

# Comment the the mysql line and uncomment the postgres line
# if you want to use postgres
choose: &choose
  # Choose one of the following
  <<: *mysql
  #<<: *postgres
  
##################################################
#### CONFIGURE ABOVE #############################
##################################################

# Normally you don't need to touch anything here

postgres_travis: &postgres_travis
  adapter: postgresql
  username: postgres
common: &common
  <<: *choose
development:
  <<: *common
  database: diaspora_development
production:
  <<: *common
  database: diaspora_production
test:
  <<: *common
  database: "diaspora_test_<%= ENV['TEST_ENV'] %>"
integration1:
  <<: *common
  database: diaspora_integration1
integration2:
  <<: *common
  database: diaspora_integration2

